version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vipjob  # You can leave this as is, or set it to your database name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - vipjob-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vipjob-node
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mysql

    command: sh -c "npx wait-on tcp:mysql:3306 && node server.js"

    networks:
      - vipjob-network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ""  # No password for root user
      DB_NAME: vipjob

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: job-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""  # No password for root user
    depends_on:
      - mysql
    networks:
      - vipjob-network

volumes:
  mysql_data:

networks:
  vipjob-network:
    driver: bridge
